### ISSUE TITLE
feat: make the "Get Started" links jump directly to the new user registration link with compelling information

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve-website#32]
The current flow has the user click the link to dashboard.trieve.ai and then they are redirected to auth (the redirect also takes time). 
Target links: Get Started (x2) on trieve.ai and Get Started Free on https://trieve.ai/pricing/

<img width="655" alt="image" src="https://github.com/user-attachments/assets/35aee58a-38fd-4f64-a5c3-27105284125f">

The actual CTA for folks getting started is a small link at the bottom of that page, which then opens a form.

<img width="627" alt="image" src="https://github.com/user-attachments/assets/3faf5d87-08bd-42ca-9b01-52adfd07cf4b">

It may be valuable also to pitch the benefits of getting started at that link, so folks don't skip out on filling out that form. Perhaps this could be a separate container with key benefits of getting started:

> Get Started with the FREE Tier
> 
> 1000 Chunks, 1 Dataset, .50 GB Storage, 500 Gen AI Messages
> You can setup a dataset with sample data, upload a your own file of chunks, or follow a demo.
> 
> [embed videos showing how it takes 30sec to setup a sample dataset, 3min(?) to upload a textfile and have it chunked]
> 
> Still unsure? Derisk with a custom demo!

**Comment by skeptrunedev** [comment]
This will be a really nice improvement and should also be fairly simple considering this page is already custom
