### ISSUE TITLE
bugfix: menu button does not work on mobile

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve-website#62]
Quick fix on mobile, the menu button does not work

![image](https://github.com/user-attachments/assets/02dc7852-2575-4f7c-b07b-726446e20137)

**Comment by danielsgriffin** [comment]
The toggle menu to display the nav in mobile is not working currently.
Tested in several iOS browsers and MacOS Safari (required clearing cache to reproduce failure), Chrome, Brave incognito.
